headless:
  keyFilePath: "/home/{USER}/.dp-cli/"
  keyFileName: "dp-cli.key"
  tokenFilePath: "/home/{USER}/.dp-cli/"
  tokenFileName: "dp-cli.token"

api:
  server: "deisi.ulusofona.pt"
  endpoints:
    assignments: "/drop-project/api/student/assignments/{ASSIGNMENT_ID}"
    current_assignment: "/drop-project/api/student/assignments/current"
    submission: "/drop-project/api/student/submissions/{SUBMISSION_ID}"
    new_submission: "/drop-project/api/student/submissions/new"

dev: # this is extremelly insecure! should be removed ASAP to force encryption!
  forceFallbackMethod: false
  enableTokenEncryption: true
